name: Build and publish Docker image

on:
  push:
    branches:
      - netdrones-main
  pull_request:
    branches:
      - netdrones-main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: netdrones/px4-flight-review
  TAG: latest

jobs:
  build_and_push:
    name: Build and push Docker image
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: app
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
